This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./2020-B002-TT1-V1.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file 2020-B002-TT1-V1.acn....done (197 entries accepted, 0 rejected).
Sorting entries.....done (1634 comparisons).
Generating output file 2020-B002-TT1-V1.acr....done (119 lines written, 0 warnings).
Output written in 2020-B002-TT1-V1.acr.
Transcript written in 2020-B002-TT1-V1.alg.
